version: '3.9'

services:
  app:
    container_name: app
    build:
      context: '.'
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8006:8006"
    volumes:
      - .:/api
      - ./certbot/conf/:/etc/letsencrypt/:ro
    stop_grace_period: "3s"
    tty: true
